### ISSUE TITLE
Write functions to obtain performance metrics

### ISSUE THREAD

**Issue by gwaygenomics** [cytodata/single-cell-classifier#26]
One output for all models (using both EBImage and raw image features) will be predicted single cell classes. 
We should write a series of functions that each script can import that take in predictions and true class labels and output a series of performance results (including performance metrics, confusion matrices, etc.)

**Comment by wagenrace** [comment]
Can this be considered done?

**Comment by gwaygenomics** [comment]
lets keep the issue open - there are many more useful performance metrics and functions that we should consider implementing

Examples:

* Code to calculate sensitivity, specificity, precision, recall
* Code to plot ROC and precision recall curves

**Comment by wagenrace** [comment]
Would it be better to make those into separate clearly defined issues?

**Comment by gwaygenomics** [comment]
if it's helpful, go for it! As a maintainer, you are welcome to design this repository as you see fit
